Login
Backtrip-org/backtrip-backoffice pull request #5
Opened 2020-04-12 16:04 UTC by Daxxxan

2020-04-12 16:20 UTC, Kwuxy requested changes

2020-04-12 16:20 UTC, Kwuxy commented on src/store/index.js
> +    access_token: 'this is the token'
Retirer la valeur par défaut et mettre ''

2020-04-12 16:25 UTC, Kwuxy approved these changes

2020-04-13 14:19 UTC, csgrdcelia approved these changes

2020-04-13 15:41 UTC, merged